# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: required
r: bioc-devel

env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - R_BUILD_ARGS="--no-manual"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

bioc_required: true

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - _R_CHECK_TIMINGS_="0"
